#!/usr/bin/env ruby
#
#  Created on 2007-11-9.
#  Copyright (c) 2007. All rights reserved.

begin
  require 'rubygems'
rescue LoadError
  # no rubygems to load, so we fail silently
end

require 'optparse'
require 'serialport'
# NOTE: the option -p/--path= is given as an example, and should probably be replaced in your application.

OPTIONS = {
  :pass => nil,
  :fail => nil,
}
MANDATORY_OPTIONS = %w(  )

parser = OptionParser.new do |opts|
  opts.banner = <<BANNER

Usage: #{File.basename($0)} [options]

Options are:
BANNER
  opts.separator ""
  opts.on("-p", "Pass"){|v| OPTIONS[:pass] = true}
  opts.on("-f", "Fail"){|v| OPTIONS[:fail] = true}
  opts.on("-h", "--help",
          "Show this help message.") { puts opts; exit }
  opts.parse!(ARGV)

  if MANDATORY_OPTIONS && MANDATORY_OPTIONS.find { |option| OPTIONS[option.to_sym].nil? }
    puts opts; exit
  end
end

module Bell
  extend self
 
  def ring
    #params for serial port
    port_str = "/dev/tty.usbserial-A6006hlr" # may be different for you
    baud_rate = 9600
    data_bits = 8
    stop_bits = 1
    parity = SerialPort::NONE
    
    begin
      sp = SerialPort.new(port_str, baud_rate, data_bits, stop_bits, parity)
      puts sp.inspect
      
      sleep 3
      
      if OPTIONS[:pass]
        sp.putc 1
      elsif OPTIONS[:fail]
        sp.putc 0
      end
      
      sp.close
    rescue Exception => e
      puts "No bell to ring."
      puts e.to_s
    end
  end
end

Bell.ring