#!/usr/bin/env ruby
#
#  Created on 2007-11-9.
#  Copyright (c) 2007. All rights reserved.

#simplest ruby program to read from arduino serial, 
#using Ruby/SerialPort library
#(http://ruby-serialport.rubyforge.org)

begin
  require 'rubygems'
  require 'serialport'
rescue LoadError
  # no rubygems to load, so we fail silently
end
# require "serialport.so"

#params for serial port
port_str = "/dev/tty.usbserial-A6006hlr" # may be different for you
baud_rate = 9600
data_bits = 8
stop_bits = 1
parity = SerialPort::NONE

sp = SerialPort.new(port_str, baud_rate, data_bits, stop_bits, parity)

#just read forever
while true do
  puts sp.getc
  # printf("%c", (sp.getc || ""))
end

sp.close