#!/bin/bash

# Annotates an image with its date

img_file=$1
width=`identify -format %w "${img_file}"`; \
convert -background '#0008' -fill white -gravity center -size ${width}x30 \
          caption:"`stat -c "%y" $1 | awk '{print $1}'`" \
          "${img_file}" +swap -gravity southeast -composite  dated_${img_file}
