#!/usr/bin/env ruby
#
#  Created on 2007-11-9.
#  Copyright (c) 2007. All rights reserved.

begin
  require 'rubygems'
rescue LoadError
  # no rubygems to load, so we fail silently
end

require 'optparse'

OPTIONS = {
  :login => nil
}
MANDATORY_OPTIONS = %w(  )

parser = OptionParser.new do |opts|
  opts.banner = <<BANNER

Usage: #{File.basename($0)} [options] hostname

Options are:
BANNER
  opts.separator ""
  opts.on("-l", "--login=name", String, "User for login if not the current user."){|v| OPTIONS[:login] = v.gsub('=', '')}
  opts.on("-h", "--help", "Show this help message.") { puts opts; exit }
  opts.parse!(ARGV)

  if MANDATORY_OPTIONS && MANDATORY_OPTIONS.find { |option| OPTIONS[option.to_sym].nil? }
    puts opts; exit
  end
end

if ARGV[0].nil?
  puts "!! You need to enter a hostname in order to send your public key !!"
  exit
end

def fmt_cmd
  cmd = "ssh"
  cmd+= " -l #{OPTIONS[:login]}" if OPTIONS[:login]
  cmd+= " #{ARGV[0]} 'mkdir -p ~/.ssh && cat - >> ~/.ssh/authorized_keys2' < ~/.ssh/id_dsa.pub"
end

system fmt_cmd

