#!/usr/bin/env ruby
#
#  Created on 2007-11-9.
#  Copyright (c) 2007. All rights reserved.

begin
  require 'rubygems'
rescue LoadError
  # no rubygems to load, so we fail silently
end

require 'optparse'

OPTIONS = {
}
MANDATORY_OPTIONS = %w(  )

parser = OptionParser.new do |opts|
  opts.banner = <<BANNER
send twitter updates from command line

Usage: #{File.basename($0)} 'message string'

Options are:
BANNER
  opts.separator ""
  opts.on("-h", "--help", "Show this help message.") { puts opts; exit }
  opts.parse!(ARGV)

  # if MANDATORY_OPTIONS && MANDATORY_OPTIONS.find { |option| OPTIONS[option.to_sym].nil? }
  #   puts opts; exit
  # end
end

def format_command(msg)
  user = File.read(ENV['TWIT_USER_PATH']) if File.exist?(ENV['TWIT_USER_PATH'])
  command = "curl -u #{user} -d status='#{msg}' http://twitter.com/statuses/update.xml &> /dev/null"
  # puts command
  command
end

system format_command(ARGV[0])
