#!/usr/bin/env ruby  

#
# get last commit message
#
b = `git show`
puts b
b = b.split("\n")

#
# push a message to twitter about this commit
#
projectdesc = File.read("#{ENV['GIT_DIR']}/description")
system("twit \"commit: #{b[4]} on project: #{projectdesc}  \"")

#
# push commits
#
# system("git push")

# audio notifiction
audiofile = "#{ENV['CLI_GOODNESS']}/git-goodness/Git_Push.aif"

#
# use the included sndplay to play notification aif file
system("sndplay '#{audiofile}'") if File.exist?("audiofile")

#
# for mp3 playback sudo port install mpg123
# system("mpg123 '#{audiofile}'") if File.exist?("audiofile")
