#!/usr/bin/env ruby
#
#  Created on 2007-11-9.
#  Copyright (c) 2007. All rights reserved.

begin
  require 'rubygems'
rescue LoadError
  # no rubygems to load, so we fail silently
end

require 'optparse'

OPTIONS = {
  :path     => '~'
}
MANDATORY_OPTIONS = %w(  )

parser = OptionParser.new do |opts|
  opts.banner = <<BANNER
A Helper action for working with gems created with the newgem gem

Usage: #{File.basename($0)} <action> [options] 

Allowable actions are: 
  refresh - will uninstall the gem, refresh the gem manifest, repackage and reinstall

Options are:
BANNER
  opts.separator ""
  opts.on("-h", "--help",
          "Show this help message.") { puts opts; exit }
  opts.parse!(ARGV)

  if MANDATORY_OPTIONS && MANDATORY_OPTIONS.find { |option| OPTIONS[option.to_sym].nil? }
    puts opts; exit
  end
end

if ARGV[0].nil?
  puts "#{File.basename($0)}: not enough arguments provided; try '#{File.basename($0)} -h' for more info"
  exit
end

path = `pwd`.chomp.split(/\//)
gemname = path.pop
pdir = path.pop

unless pdir == "gems"
  puts "This does not apear to be a gem direcotry"
  exit
end

case ARGV[0]
when 'refresh'
  system "sudo gem uninstall #{gemname}"
  system "rake manifest:refresh"
  system "rake package"
  system "sudo gem install pkg/#{gemname}"
end