#!/usr/bin/env ruby
#
#  Created on 2007-11-9.
#  Copyright (c) 2007. All rights reserved.

begin
  require 'rubygems'
rescue LoadError
  # no rubygems to load, so we fail silently
end

require 'optparse'

# NOTE: the option -p/--path= is given as an example, and should probably be replaced in your application.

OPTIONS = {
  :path     => '~',
  :external => false,
  :force    => false
}
MANDATORY_OPTIONS = %w(  )

parser = OptionParser.new do |opts|
  opts.banner = <<BANNER
This application is wonderful because...

Usage: #{File.basename($0)} [options]

Options are:
BANNER
  opts.separator ""
  opts.on("-f", "--force", "Force reinstall of existing plugins") { OPTIONS[:force] = true }
  opts.on("-x", "--install-external", "Install Plugins as svn externals") { OPTIONS[:external] = true }
  opts.on("-h", "--help",
          "Show this help message.") { puts opts; exit }
  opts.parse!(ARGV)

  if MANDATORY_OPTIONS && MANDATORY_OPTIONS.find { |option| OPTIONS[option.to_sym].nil? }
    puts opts; exit
  end
end

def format_command(plugin)
  command = "ruby script/plugin install "
  command += "-x " if OPTIONS[:external]
  command += "--force " if OPTIONS[:force]
  command += "#{plugin}"
  return command
end

system "progress_header \"Install plugin - #{ARGV[0]}\""
system format_command(ARGV[0])
