#!/usr/bin/env ruby
#
#  Created on 2007-11-9.
#  Copyright (c) 2007. All rights reserved.

begin
  require 'rubygems'
rescue LoadError
  # no rubygems to load, so we fail silently
end

require 'optparse'

# NOTE: the option -p/--path= is given as an example, and should probably be replaced in your application.

OPTIONS = {
}
MANDATORY_OPTIONS = %w(  )

parser = OptionParser.new do |opts|
  opts.banner = <<BANNER
Clean a directory structure recursively of all dreamweaver _notes directories

Usage: #{File.basename($0)} [options]

Options are:
BANNER
  opts.separator ""
  opts.on("-h", "--help",
          "Show this help message.") { puts opts; exit }
  opts.parse!(ARGV)

  if MANDATORY_OPTIONS && MANDATORY_OPTIONS.find { |option| OPTIONS[option.to_sym].nil? }
    puts opts; exit
  end
end

MESSAGE = [
  "Are you sure you wish to purge this directory and all subdirectories _notes? ",
  "type 'yes' or 'no'"  
]

def prompt(num=0)
  puts MESSAGE[num]
  @confirm = $stdin.gets.chomp 
  
  if @confirm == "yes" || @confirm == "no"
    return
  else
    prompt(1)
  end

end

def svn_sweep
  prompt

  if @confirm == "yes"
    system "find . -type d -name '_notes' -exec rm -rf {} \\;"
    exit
  elsif @confirm == "no"
    exit
  end
  
end

svn_sweep